CREATE OR REPLACE PROCEDURE INCLUIR_CLIENTE(
p_NOME_CLIENTE CLIENTES.NOME_CLIENTE%TYPE)
IS
BEGIN
            INSERT INTO CLIENTES VALUES (SEQUENCE_CLIENTES.NEXTVAL, p_NOME_CLIENTE, SYSDATE );
END;


EXECUTE projeto.INCLUIR_CLIENTE('Cleuza Aparecida');
