
--Linha 1
INSERT INTO CLIENTES (ID_CLIENTE, NOME_CLIENTE, DATA_CADASTRO) VALUES (SEQUENCE_CLIENTES.NEXTVAL,'Maria José',to_timestamp('29/01/2021 01:58', 'YYYY-MM-DD HH24:MI:SS'));
--Linha 2
INSERT INTO CLIENTES (ID_CLIENTE,  NOME_CLIENTE, DATA_CADASTRO) VALUES (SEQUENCE_CLIENTES.NEXTVAL,'Otávio Duarte',to_timestamp('29/01/2021 01:58', 'YYYY-MM-DD HH24:MI:SS'));
--Linha 3
INSERT INTO CLIENTES (ID_CLIENTE,  NOME_CLIENTE, DATA_CADASTRO) VALUES (SEQUENCE_CLIENTES.NEXTVAL,'Melissa Borges',to_timestamp('29/01/2021 01:58', 'YYYY-MM-DD HH24:MI:SS'));
--Linha 4
INSERT INTO CLIENTES (ID_CLIENTE,  NOME_CLIENTE, DATA_CADASTRO) VALUES (SEQUENCE_CLIENTES.NEXTVAL,'Tamara Moura',to_timestamp('29/01/2021 01:58', 'YYYY-MM-DD HH24:MI:SS'));
--Linha 5
INSERT INTO CLIENTES (ID_CLIENTE, NOME_CLIENTE, DATA_CADASTRO) VALUES (SEQUENCE_CLIENTES.NEXTVAL,'Oswaldo Neves',to_timestamp('29/01/2021 01:58', 'YYYY-MM-DD HH24:MI:SS'));
--Linha 6
INSERT INTO CLIENTES (ID_CLIENTE, NOME_CLIENTE, DATA_CADASTRO) VALUES (SEQUENCE_CLIENTES.NEXTVAL,'Lúcio Mário',to_timestamp('29/01/2021 01:58', 'YYYY-MM-DD HH24:MI:SS'));
--Linha 7
INSERT INTO CLIENTES (ID_CLIENTE, NOME_CLIENTE, DATA_CADASTRO) VALUES (SEQUENCE_CLIENTES.NEXTVAL,'Abraham Estevam',to_timestamp('29/01/2021 01:58', 'YYYY-MM-DD HH24:MI:SS'));
--Linha 8
INSERT INTO CLIENTES (ID_CLIENTE, NOME_CLIENTE, DATA_CADASTRO) VALUES (SEQUENCE_CLIENTES.NEXTVAL,'Joane Castro',to_timestamp('29/01/2021 01:58', 'YYYY-MM-DD HH24:MI:SS'));
--Linha 9
INSERT INTO CLIENTES (ID_CLIENTE, NOME_CLIENTE, DATA_CADASTRO) VALUES (SEQUENCE_CLIENTES.NEXTVAL,'Victor Mesquita',to_timestamp('29/01/2021 01:58', 'YYYY-MM-DD HH24:MI:SS'));
