
--Linha 1
INSERT INTO PRODUTOS ( ID_PRODUTO, NOME_PRODUTO, ID_FORNECEDOR, DATA_CADASTRO, CATEGORIA_PRODUTO, VALOR_PRODUTO) VALUES (SEQUENCE_PRODUTOS.nextval, 'Arroz',4,to_timestamp('29/01/2021 02:30', 'YYYY-MM-DD HH24:MI:SS'),'Mercearia',30.6);
--Linha 2
INSERT INTO PRODUTOS ( ID_PRODUTO, NOME_PRODUTO, ID_FORNECEDOR, DATA_CADASTRO, CATEGORIA_PRODUTO, VALOR_PRODUTO) VALUES (SEQUENCE_PRODUTOS.nextval,'Feijão',4,to_timestamp('29/01/2021 02:30', 'YYYY-MM-DD HH24:MI:SS'),'Mercearia',15.1);
--Linha 3
INSERT INTO PRODUTOS ( ID_PRODUTO, NOME_PRODUTO, ID_FORNECEDOR, DATA_CADASTRO, CATEGORIA_PRODUTO, VALOR_PRODUTO) VALUES (SEQUENCE_PRODUTOS.nextval,'Óleo',4,to_timestamp('29/01/2021 02:30', 'YYYY-MM-DD HH24:MI:SS'),'Mercearia',9.99);
--Linha 4
INSERT INTO PRODUTOS ( ID_PRODUTO, NOME_PRODUTO, ID_FORNECEDOR, DATA_CADASTRO, CATEGORIA_PRODUTO, VALOR_PRODUTO) VALUES (SEQUENCE_PRODUTOS.nextval,'Macarrão',4,to_timestamp('29/01/2021 02:30', 'YYYY-MM-DD HH24:MI:SS'),'Mercearia',2.6);
--Linha 5
INSERT INTO PRODUTOS ( ID_PRODUTO, NOME_PRODUTO, ID_FORNECEDOR, DATA_CADASTRO, CATEGORIA_PRODUTO, VALOR_PRODUTO) VALUES (SEQUENCE_PRODUTOS.nextval,'Sardinha',11,to_timestamp('29/01/2021 02:30', 'YYYY-MM-DD HH24:MI:SS'),'Mercearia',1.3);
--Linha 6
INSERT INTO PRODUTOS ( ID_PRODUTO, NOME_PRODUTO, ID_FORNECEDOR, DATA_CADASTRO, CATEGORIA_PRODUTO, VALOR_PRODUTO) VALUES (SEQUENCE_PRODUTOS.nextval,'Farinha de Trigo',2,to_timestamp('29/01/2021 02:30', 'YYYY-MM-DD HH24:MI:SS'),'Mercearia',1.0);
--Linha 7
INSERT INTO PRODUTOS ( ID_PRODUTO, NOME_PRODUTO, ID_FORNECEDOR, DATA_CADASTRO, CATEGORIA_PRODUTO, VALOR_PRODUTO) VALUES (SEQUENCE_PRODUTOS.nextval,'Farinha de Rosca',2,to_timestamp('29/01/2021 02:30', 'YYYY-MM-DD HH24:MI:SS'),'Mercearia',1.0);
--Linha 8
INSERT INTO PRODUTOS ( ID_PRODUTO, NOME_PRODUTO, ID_FORNECEDOR, DATA_CADASTRO, CATEGORIA_PRODUTO, VALOR_PRODUTO) VALUES (SEQUENCE_PRODUTOS.nextval,'Fubá',2,to_timestamp('29/01/2021 02:30', 'YYYY-MM-DD HH24:MI:SS'),'Mercearia',1.0);
--Linha 9
INSERT INTO PRODUTOS ( ID_PRODUTO, NOME_PRODUTO, ID_FORNECEDOR, DATA_CADASTRO, CATEGORIA_PRODUTO, VALOR_PRODUTO) VALUES (SEQUENCE_PRODUTOS.nextval,'Maizena',2,to_timestamp('29/01/2021 02:30', 'YYYY-MM-DD HH24:MI:SS'),'Mercearia',3.1);
--Linha 10
INSERT INTO PRODUTOS ( ID_PRODUTO, NOME_PRODUTO, ID_FORNECEDOR, DATA_CADASTRO, CATEGORIA_PRODUTO, VALOR_PRODUTO) VALUES (SEQUENCE_PRODUTOS.nextval,'Bolacha Cream Cracker',9,to_timestamp('29/01/2021 02:30', 'YYYY-MM-DD HH24:MI:SS'),'Mercearia',5.9);
--Linha 11
INSERT INTO PRODUTOS ( ID_PRODUTO, NOME_PRODUTO, ID_FORNECEDOR, DATA_CADASTRO, CATEGORIA_PRODUTO, VALOR_PRODUTO) VALUES (SEQUENCE_PRODUTOS.nextval,'Bolacha Recheada',9,to_timestamp('29/01/2021 02:30', 'YYYY-MM-DD HH24:MI:SS'),'Mercearia',3.75);
--Linha 12
INSERT INTO PRODUTOS ( ID_PRODUTO, NOME_PRODUTO, ID_FORNECEDOR, DATA_CADASTRO, CATEGORIA_PRODUTO, VALOR_PRODUTO) VALUES (SEQUENCE_PRODUTOS.nextval,'Achocolatado em Pó',9,to_timestamp('29/01/2021 02:30', 'YYYY-MM-DD HH24:MI:SS'),'Mercearia',9.49);
--Linha 13
INSERT INTO PRODUTOS ( ID_PRODUTO, NOME_PRODUTO, ID_FORNECEDOR, DATA_CADASTRO, CATEGORIA_PRODUTO, VALOR_PRODUTO) VALUES (SEQUENCE_PRODUTOS.nextval,'Detergente',10,to_timestamp('29/01/2021 02:30', 'YYYY-MM-DD HH24:MI:SS'),'Limpeza',2.39);
--Linha 14
INSERT INTO PRODUTOS ( ID_PRODUTO, NOME_PRODUTO, ID_FORNECEDOR, DATA_CADASTRO, CATEGORIA_PRODUTO, VALOR_PRODUTO) VALUES (SEQUENCE_PRODUTOS.nextval,'Esponja',10,to_timestamp('29/01/2021 02:30', 'YYYY-MM-DD HH24:MI:SS'),'Limpeza',0.99);
--Linha 15
INSERT INTO PRODUTOS ( ID_PRODUTO, NOME_PRODUTO, ID_FORNECEDOR, DATA_CADASTRO, CATEGORIA_PRODUTO, VALOR_PRODUTO) VALUES (SEQUENCE_PRODUTOS.nextval,'Sabonete',8,to_timestamp('29/01/2021 02:30', 'YYYY-MM-DD HH24:MI:SS'),'Higiene Pessoal',2.29);
--Linha 16
INSERT INTO PRODUTOS ( ID_PRODUTO, NOME_PRODUTO, ID_FORNECEDOR, DATA_CADASTRO, CATEGORIA_PRODUTO, VALOR_PRODUTO) VALUES (SEQUENCE_PRODUTOS.nextval,'Papel Higiênico',8,to_timestamp('29/01/2021 02:30', 'YYYY-MM-DD HH24:MI:SS'),'Higiene Pessoal',26.9);
--Linha 17
INSERT INTO PRODUTOS ( ID_PRODUTO, NOME_PRODUTO, ID_FORNECEDOR, DATA_CADASTRO, CATEGORIA_PRODUTO, VALOR_PRODUTO) VALUES (SEQUENCE_PRODUTOS.nextval,'Creme Dental',8,to_timestamp('29/01/2021 02:30', 'YYYY-MM-DD HH24:MI:SS'),'Higiene Pessoal',2.49);
--Linha 18
INSERT INTO PRODUTOS ( ID_PRODUTO, NOME_PRODUTO, ID_FORNECEDOR, DATA_CADASTRO, CATEGORIA_PRODUTO, VALOR_PRODUTO) VALUES (SEQUENCE_PRODUTOS.nextval,'Sabão em Pó',10,to_timestamp('29/01/2021 02:30', 'YYYY-MM-DD HH24:MI:SS'),'Limpeza',50.9);
--Linha 19
INSERT INTO PRODUTOS ( ID_PRODUTO, NOME_PRODUTO, ID_FORNECEDOR, DATA_CADASTRO, CATEGORIA_PRODUTO, VALOR_PRODUTO) VALUES (SEQUENCE_PRODUTOS.nextval,'Desinfetante',10,to_timestamp('29/01/2021 02:30', 'YYYY-MM-DD HH24:MI:SS'),'Limpeza',7.3);
--Linha 20
INSERT INTO PRODUTOS ( ID_PRODUTO, NOME_PRODUTO, ID_FORNECEDOR, DATA_CADASTRO, CATEGORIA_PRODUTO, VALOR_PRODUTO) VALUES (SEQUENCE_PRODUTOS.nextval,'Água Sanitária',1,to_timestamp('29/01/2021 02:30', 'YYYY-MM-DD HH24:MI:SS'),'Limpeza',2.79);
--Linha 21
INSERT INTO PRODUTOS ( ID_PRODUTO, NOME_PRODUTO, ID_FORNECEDOR, DATA_CADASTRO, CATEGORIA_PRODUTO, VALOR_PRODUTO) VALUES (SEQUENCE_PRODUTOS.nextval,'Suco em Pó',3,to_timestamp('29/01/2021 02:30', 'YYYY-MM-DD HH24:MI:SS'),'Mercearia',0.79);
--Linha 22
INSERT INTO PRODUTOS ( ID_PRODUTO, NOME_PRODUTO, ID_FORNECEDOR, DATA_CADASTRO, CATEGORIA_PRODUTO, VALOR_PRODUTO) VALUES (SEQUENCE_PRODUTOS.nextval,'Margarina',6,to_timestamp('29/01/2021 02:30', 'YYYY-MM-DD HH24:MI:SS'),'Mercearia',3.3);
--Linha 23
INSERT INTO PRODUTOS ( ID_PRODUTO, NOME_PRODUTO, ID_FORNECEDOR, DATA_CADASTRO, CATEGORIA_PRODUTO, VALOR_PRODUTO) VALUES (SEQUENCE_PRODUTOS.nextval,'Manteiga',6,to_timestamp('29/01/2021 02:30', 'YYYY-MM-DD HH24:MI:SS'),'Mercearia',6.2);
--Linha 24
INSERT INTO PRODUTOS ( ID_PRODUTO, NOME_PRODUTO, ID_FORNECEDOR, DATA_CADASTRO, CATEGORIA_PRODUTO, VALOR_PRODUTO) VALUES (SEQUENCE_PRODUTOS.nextval,'Mistura para Bolo',7,to_timestamp('29/01/2021 02:30', 'YYYY-MM-DD HH24:MI:SS'),'Mercearia',5.5);
--Linha 25
INSERT INTO PRODUTOS ( ID_PRODUTO, NOME_PRODUTO, ID_FORNECEDOR, DATA_CADASTRO, CATEGORIA_PRODUTO, VALOR_PRODUTO) VALUES (SEQUENCE_PRODUTOS.nextval,'Milho para Pipoca',12,to_timestamp('29/01/2021 02:30', 'YYYY-MM-DD HH24:MI:SS'),'Mercearia',1.39);
--Linha 26
INSERT INTO PRODUTOS ( ID_PRODUTO, NOME_PRODUTO, ID_FORNECEDOR, DATA_CADASTRO, CATEGORIA_PRODUTO, VALOR_PRODUTO) VALUES (SEQUENCE_PRODUTOS.nextval,'Molho de Tomate',7,to_timestamp('29/01/2021 02:30', 'YYYY-MM-DD HH24:MI:SS'),'Mercearia',0.89);
--Linha 27
INSERT INTO PRODUTOS ( ID_PRODUTO, NOME_PRODUTO, ID_FORNECEDOR, DATA_CADASTRO, CATEGORIA_PRODUTO, VALOR_PRODUTO) VALUES (SEQUENCE_PRODUTOS.nextval,'Sal',13,to_timestamp('29/01/2021 02:30', 'YYYY-MM-DD HH24:MI:SS'),'Mercearia',5.39);
--Linha 28
INSERT INTO PRODUTOS ( ID_PRODUTO, NOME_PRODUTO, ID_FORNECEDOR, DATA_CADASTRO, CATEGORIA_PRODUTO, VALOR_PRODUTO) VALUES (SEQUENCE_PRODUTOS.nextval,'Açúcar',5,to_timestamp('29/01/2021 02:30', 'YYYY-MM-DD HH24:MI:SS'),'Mercearia',12.29);
--Linha 29
INSERT INTO PRODUTOS ( ID_PRODUTO, NOME_PRODUTO, ID_FORNECEDOR, DATA_CADASTRO, CATEGORIA_PRODUTO, VALOR_PRODUTO) VALUES (SEQUENCE_PRODUTOS.nextval,'Amaciante',10,to_timestamp('29/01/2021 02:30', 'YYYY-MM-DD HH24:MI:SS'),'Limpeza',17.99);
--Linha 30
INSERT INTO PRODUTOS ( ID_PRODUTO, NOME_PRODUTO, ID_FORNECEDOR, DATA_CADASTRO, CATEGORIA_PRODUTO, VALOR_PRODUTO) VALUES (SEQUENCE_PRODUTOS.nextval,'Limpador Multi Uso',10,to_timestamp('29/01/2021 02:30', 'YYYY-MM-DD HH24:MI:SS'),'Limpeza',3.49);
