
INSERT INTO ESTOQUE (ID_PRODUTO, QUANTIDADE) VALUES (1,85);
--Linha 2
INSERT INTO ESTOQUE (ID_PRODUTO, QUANTIDADE) VALUES (2,100);
--Linha 3
INSERT INTO ESTOQUE (ID_PRODUTO, QUANTIDADE) VALUES (3,301);
--Linha 4
INSERT INTO ESTOQUE (ID_PRODUTO, QUANTIDADE) VALUES (4,144);
--Linha 5
INSERT INTO ESTOQUE (ID_PRODUTO, QUANTIDADE) VALUES (5,77);
--Linha 6
INSERT INTO ESTOQUE (ID_PRODUTO, QUANTIDADE) VALUES (6,108);
--Linha 7
INSERT INTO ESTOQUE (ID_PRODUTO, QUANTIDADE) VALUES (7,249);
--Linha 8
INSERT INTO ESTOQUE (ID_PRODUTO, QUANTIDADE) VALUES (8,165);
--Linha 9
INSERT INTO ESTOQUE (ID_PRODUTO, QUANTIDADE) VALUES (9,269);
--Linha 10
INSERT INTO ESTOQUE (ID_PRODUTO, QUANTIDADE) VALUES (10,204);
--Linha 11
INSERT INTO ESTOQUE (ID_PRODUTO, QUANTIDADE) VALUES (11,194);
--Linha 12
INSERT INTO ESTOQUE (ID_PRODUTO, QUANTIDADE) VALUES (12,95);
--Linha 13
INSERT INTO ESTOQUE (ID_PRODUTO, QUANTIDADE) VALUES (13,90);
--Linha 14
INSERT INTO ESTOQUE (ID_PRODUTO, QUANTIDADE) VALUES (14,266);
--Linha 15
INSERT INTO ESTOQUE (ID_PRODUTO, QUANTIDADE) VALUES (15,113);
--Linha 16
INSERT INTO ESTOQUE (ID_PRODUTO, QUANTIDADE) VALUES (16,136);
--Linha 17
INSERT INTO ESTOQUE (ID_PRODUTO, QUANTIDADE) VALUES (17,97);
--Linha 18
INSERT INTO ESTOQUE (ID_PRODUTO, QUANTIDADE) VALUES (18,259);
--Linha 19
INSERT INTO ESTOQUE (ID_PRODUTO, QUANTIDADE) VALUES (19,264);
--Linha 20
INSERT INTO ESTOQUE (ID_PRODUTO, QUANTIDADE) VALUES (20,99);
--Linha 21
INSERT INTO ESTOQUE (ID_PRODUTO, QUANTIDADE) VALUES (21,74);
--Linha 22
INSERT INTO ESTOQUE (ID_PRODUTO, QUANTIDADE) VALUES (22,295);
--Linha 23
INSERT INTO ESTOQUE (ID_PRODUTO, QUANTIDADE) VALUES (23,127);
--Linha 24
INSERT INTO ESTOQUE (ID_PRODUTO, QUANTIDADE) VALUES (24,124);
--Linha 25
INSERT INTO ESTOQUE (ID_PRODUTO, QUANTIDADE) VALUES (25,277);
--Linha 26
INSERT INTO ESTOQUE (ID_PRODUTO, QUANTIDADE) VALUES (26,134);
--Linha 27
INSERT INTO ESTOQUE (ID_PRODUTO, QUANTIDADE) VALUES (27,306);
--Linha 28
INSERT INTO ESTOQUE (ID_PRODUTO, QUANTIDADE) VALUES (28,281);
--Linha 29
INSERT INTO ESTOQUE (ID_PRODUTO, QUANTIDADE) VALUES (29,143);
--Linha 30
INSERT INTO ESTOQUE (ID_PRODUTO, QUANTIDADE) VALUES (30,110);

--atualizando a reserva do estoque
DECLARE 
    CURSOR CUR_QUANTIDADE IS SELECT ID_PRODUTO FROM ITEM_PEDIDOS;
BEGIN 
     FOR IDENTIFICACAO IN CUR_QUANTIDADE LOOP
                projeto.atualiza_reserva(IDENTIFICACAO.ID_PRODUTO);
     END LOOP;
END;
