
--Linha 1
INSERT INTO FORNECEDORES (ID_FORNECEDOR, NOME_FORNECEDOR, NOME_MARCA) VALUES (SEQUENCE_FORNECEDORES.NEXTVAL, 'João Lucas','Amarelim');
--Linha 2
INSERT INTO FORNECEDORES (ID_FORNECEDOR, NOME_FORNECEDOR, NOME_MARCA) VALUES (SEQUENCE_FORNECEDORES.NEXTVAL, 'João Carlos','Amió');
--Linha 3
INSERT INTO FORNECEDORES (ID_FORNECEDOR,  NOME_FORNECEDOR, NOME_MARCA) VALUES (SEQUENCE_FORNECEDORES.NEXTVAL, 'Maria Antonieta','Bang');
--Linha 4
INSERT INTO FORNECEDORES (ID_FORNECEDOR,  NOME_FORNECEDOR, NOME_MARCA) VALUES (SEQUENCE_FORNECEDORES.NEXTVAL, 'José Marcos','Cocais');
--Linha 5
INSERT INTO FORNECEDORES (ID_FORNECEDOR,  NOME_FORNECEDOR, NOME_MARCA) VALUES (SEQUENCE_FORNECEDORES.NEXTVAL, 'Mário Carlos','Docinho');
--Linha 6
INSERT INTO FORNECEDORES (ID_FORNECEDOR,  NOME_FORNECEDOR, NOME_MARCA) VALUES (SEQUENCE_FORNECEDORES.NEXTVAL, 'André Getúlio','Ducel');
--Linha 7
INSERT INTO FORNECEDORES (ID_FORNECEDOR,  NOME_FORNECEDOR, NOME_MARCA) VALUES (SEQUENCE_FORNECEDORES.NEXTVAL, 'Ana Maria Barra','Helena');
--Linha 8
INSERT INTO FORNECEDORES (ID_FORNECEDOR,  NOME_FORNECEDOR, NOME_MARCA) VALUES (SEQUENCE_FORNECEDORES.NEXTVAL, 'Gabriella Menez','JJ');
--Linha 9
INSERT INTO FORNECEDORES (ID_FORNECEDOR,  NOME_FORNECEDOR, NOME_MARCA) VALUES (SEQUENCE_FORNECEDORES.NEXTVAL, 'Victória Machado','Kito');
--Linha 10
INSERT INTO FORNECEDORES (ID_FORNECEDOR,  NOME_FORNECEDOR, NOME_MARCA) VALUES (SEQUENCE_FORNECEDORES.NEXTVAL, 'Paulo Antunes','Lírio');
--Linha 11
INSERT INTO FORNECEDORES (ID_FORNECEDOR,  NOME_FORNECEDOR, NOME_MARCA) VALUES (SEQUENCE_FORNECEDORES.NEXTVAL, 'Geralda Maria','Náutica');
--Linha 12
INSERT INTO FORNECEDORES (ID_FORNECEDOR,  NOME_FORNECEDOR, NOME_MARCA) VALUES (SEQUENCE_FORNECEDORES.NEXTVAL, 'Antonio José','Paqua');
--Linha 13
INSERT INTO FORNECEDORES (ID_FORNECEDOR,  NOME_FORNECEDOR, NOME_MARCA) VALUES (SEQUENCE_FORNECEDORES.NEXTVAL, 'Francisco Manoel','Tubarão');
