
INSERT INTO PEDIDOS (ID_PEDIDO, DATA_PEDIDO, ID_CLIENTE) VALUES (SEQUENCE_PEDIDOS.nextval,to_timestamp('11/11/2020', 'DD/MM/YYYY'),7);

INSERT INTO PEDIDOS (ID_PEDIDO, DATA_PEDIDO, ID_CLIENTE) VALUES (SEQUENCE_PEDIDOS.nextval,to_timestamp('12/12/2020', 'DD/MM/YYYY'),7);

INSERT INTO PEDIDOS (ID_PEDIDO, DATA_PEDIDO, ID_CLIENTE) VALUES (SEQUENCE_PEDIDOS.nextval,to_timestamp('20/01/2021', 'DD/MM/YYYY'),7);

INSERT INTO PEDIDOS (ID_PEDIDO, DATA_PEDIDO, ID_CLIENTE) VALUES (SEQUENCE_PEDIDOS.nextval,to_timestamp('22/01/2021', 'DD/MM/YYYY'),7);

INSERT INTO PEDIDOS (ID_PEDIDO, DATA_PEDIDO, ID_CLIENTE) VALUES (SEQUENCE_PEDIDOS.nextval,to_timestamp('01/01/2021', 'DD/MM/YYYY'),8);

INSERT INTO PEDIDOS (ID_PEDIDO, DATA_PEDIDO, ID_CLIENTE) VALUES (SEQUENCE_PEDIDOS.nextval,to_timestamp('22/01/2021', 'DD/MM/YYYY'),8);

INSERT INTO PEDIDOS (ID_PEDIDO, DATA_PEDIDO, ID_CLIENTE) VALUES (SEQUENCE_PEDIDOS.nextval,to_timestamp('22/01/2021', 'DD/MM/YYYY'),8);

INSERT INTO PEDIDOS (ID_PEDIDO, DATA_PEDIDO, ID_CLIENTE) VALUES (SEQUENCE_PEDIDOS.nextval,to_timestamp('12/12/2020', 'DD/MM/YYYY'),6);

INSERT INTO PEDIDOS (ID_PEDIDO, DATA_PEDIDO, ID_CLIENTE) VALUES (SEQUENCE_PEDIDOS.nextval,to_timestamp('20/01/2021', 'DD/MM/YYYY'),6);

INSERT INTO PEDIDOS (ID_PEDIDO, DATA_PEDIDO, ID_CLIENTE) VALUES (SEQUENCE_PEDIDOS.nextval,to_timestamp('22/01/2021', 'DD/MM/YYYY'),6);

INSERT INTO PEDIDOS (ID_PEDIDO, DATA_PEDIDO, ID_CLIENTE) VALUES (SEQUENCE_PEDIDOS.nextval,to_timestamp('12/12/2020', 'DD/MM/YYYY'),1);

INSERT INTO PEDIDOS (ID_PEDIDO, DATA_PEDIDO, ID_CLIENTE) VALUES (SEQUENCE_PEDIDOS.nextval,to_timestamp('22/01/2021', 'DD/MM/YYYY'),1);

INSERT INTO PEDIDOS (ID_PEDIDO, DATA_PEDIDO, ID_CLIENTE) VALUES (SEQUENCE_PEDIDOS.nextval,to_timestamp('01/01/2021', 'DD/MM/YYYY'),3);

INSERT INTO PEDIDOS (ID_PEDIDO, DATA_PEDIDO, ID_CLIENTE) VALUES (SEQUENCE_PEDIDOS.nextval,to_timestamp('20/01/2021', 'DD/MM/YYYY'),3);

INSERT INTO PEDIDOS (ID_PEDIDO, DATA_PEDIDO, ID_CLIENTE) VALUES (SEQUENCE_PEDIDOS.nextval,to_timestamp('01/01/2021', 'DD/MM/YYYY'),5);

INSERT INTO PEDIDOS (ID_PEDIDO, DATA_PEDIDO, ID_CLIENTE) VALUES (SEQUENCE_PEDIDOS.nextval,to_timestamp('20/01/2021', 'DD/MM/YYYY'),5);

INSERT INTO PEDIDOS (ID_PEDIDO, DATA_PEDIDO, ID_CLIENTE) VALUES (SEQUENCE_PEDIDOS.nextval,to_timestamp('25/12/2020', 'DD/MM/YYYY'),5);

INSERT INTO PEDIDOS (ID_PEDIDO, DATA_PEDIDO, ID_CLIENTE) VALUES (SEQUENCE_PEDIDOS.nextval,to_timestamp('20/01/2021', 'DD/MM/YYYY'),2);

INSERT INTO PEDIDOS (ID_PEDIDO, DATA_PEDIDO, ID_CLIENTE) VALUES (SEQUENCE_PEDIDOS.nextval,to_timestamp('25/12/2020', 'DD/MM/YYYY'),2);

INSERT INTO PEDIDOS (ID_PEDIDO, DATA_PEDIDO, ID_CLIENTE) VALUES (SEQUENCE_PEDIDOS.nextval,to_timestamp('01/01/2021', 'DD/MM/YYYY'),4);

INSERT INTO PEDIDOS (ID_PEDIDO, DATA_PEDIDO, ID_CLIENTE) VALUES (SEQUENCE_PEDIDOS.nextval,to_timestamp('12/12/2020', 'DD/MM/YYYY'),4);

INSERT INTO PEDIDOS (ID_PEDIDO, DATA_PEDIDO, ID_CLIENTE) VALUES (SEQUENCE_PEDIDOS.nextval,to_timestamp('20/01/2021', 'DD/MM/YYYY'),4);

INSERT INTO PEDIDOS (ID_PEDIDO, DATA_PEDIDO, ID_CLIENTE) VALUES (SEQUENCE_PEDIDOS.nextval,to_timestamp('22/01/2021', 'DD/MM/YYYY'),4);

INSERT INTO PEDIDOS (ID_PEDIDO, DATA_PEDIDO, ID_CLIENTE) VALUES (SEQUENCE_PEDIDOS.nextval,to_timestamp('25/12/2020', 'DD/MM/YYYY'),4);

INSERT INTO PEDIDOS (ID_PEDIDO, DATA_PEDIDO, ID_CLIENTE) VALUES (SEQUENCE_PEDIDOS.nextval,to_timestamp('11/11/2020', 'DD/MM/YYYY'),9);

INSERT INTO PEDIDOS (ID_PEDIDO, DATA_PEDIDO, ID_CLIENTE) VALUES (SEQUENCE_PEDIDOS.nextval,to_timestamp('12/12/2020', 'DD/MM/YYYY'),9);

UPDATE PEDIDOS SET STATUS_PEDIDO = 'Reservado'; -- atualizar status do pedido para reservado (antes estava nulo)