CREATE TABLE FORNECEDORES 
(
    ID_FORNECEDOR NUMBER(18),
    NOME_FORNECEDOR VARCHAR2 (50),
    NOME_MARCA VARCHAR2 (30)
)
ALTER TABLE FORNECEDORES
ADD CONSTRAINT FORNECEDOR_PK
PRIMARY KEY (ID_FORNECEDOR);

CREATE TABLE PRODUTOS 
(
    ID_PRODUTO NUMBER(18),
    NOME_PRODUTO VARCHAR2(25),
    ID_FORNECEDOR NUMBER(18),
    DATA_CADASTRO TIMESTAMP,
    CATEGORIA_PRODUTO VARCHAR2 (15),
    VALOR_PRODUTO NUMBER(5,2)
)
ALTER TABLE PRODUTOS
ADD CONSTRAINT PRODUTOS_PK 
PRIMARY KEY (ID_PRODUTO);

ALTER TABLE PRODUTOS 
ADD CONSTRAINT PRODUTO_FK_FORNECEDOR 
FOREIGN KEY (ID_FORNECEDOR)
REFERENCES FORNECEDORES (ID_FORNECEDOR);

CREATE TABLE ESTOQUE 
(
    ID_PRODUTO NUMBER(18),
    QUANTIDADE NUMBER(10),
    RESERVA NUMBER(10)
)
ALTER TABLE ESTOQUE 
ADD CONSTRAINT ESTOQUE_PK 
PRIMARY KEY (ID_PRODUTO);

ALTER TABLE ESTOQUE
ADD CONSTRAINT ESTOQUE_FK_PRODUTOS 
FOREIGN KEY (ID_PRODUTO)
REFERENCES PRODUTOS(ID_PRODUTO);

CREATE TABLE CLIENTES
(
    ID_CLIENTE NUMBER(18),
    NOME_CLIENTE VARCHAR2 (25),
    DATA_CADASTRO TIMESTAMP
);
ALTER TABLE CLIENTES 
ADD CONSTRAINT CLIENTES_PK
PRIMARY KEY (ID_CLIENTE);

CREATE TABLE PEDIDOS 
(
    ID_PEDIDO NUMBER(18),
    ID_CLIENTE NUMBER(18),
    DATA_PEDIDO TIMESTAMP,
    STATUS_PEDIDO VARCHAR2 (10)
    
)
ALTER TABLE PEDIDOS 
ADD CONSTRAINT PEDIDOS_PK 
PRIMARY KEY (ID_PEDIDO);

ALTER TABLE PEDIDOS
ADD CONSTRAINT PEDIDOS_FK_CLIENTES
FOREIGN KEY (ID_CLIENTE)
REFERENCES CLIENTES(ID_CLIENTE);

CREATE TABLE ITEM_PEDIDOS
(
    ID_PEDIDO NUMBER (18),
    ID_ITEM_PEDIDO NUMBER (18),
    ID_PRODUTO NUMBER(18),
    QUANTIDADE NUMBER(10)
    
)
ALTER TABLE ITEM_PEDIDOS
ADD CONSTRAINT ITEM_PEDIDOS_PK
PRIMARY KEY (ID_PEDIDO, ID_ITEM_PEDIDO);

ALTER TABLE ITEM_PEDIDOS 
ADD CONSTRAINT ITEM_PEDIDOS_FK_PEDIDOS
FOREIGN KEY (ID_PEDIDO)
REFERENCES PEDIDOS(ID_PEDIDO);

ALTER TABLE ITEM_PEDIDOS
ADD CONSTRAINT ITEM_PEDIDOS_FK_PRODUTOS
FOREIGN KEY (ID_PRODUTO)
REFERENCES PRODUTOS(ID_PRODUTO);
